### PR TITLE
findSequenceOnDisk: add preserve_padding option to apply original padding characters to matching sequence (refs #112)

### LINKED ISSUE #112: FileSequence.findSequenceOnDisk changes padding style unless called with strictPadding=True
`FileSequence.findSequenceOnDisk('/path/to/file.$F.exr')` returns a FileSequence with padding '#' instead of '$F'.

It seems like it would be fine without the `and strictPadding` on https://github.com/justinfx/fileseq/blob/master/src/fileseq/filesequence.py#L1123

according to the docstring for strictPadding ( `if True, ignore files with padding length different from pattern`) I would not expect it to have an effect on the padding style, unless maybe the padding style from the match happens to be incompatible with the padding from the pattern ?

### PR DESCRIPTION
**Pull request by justinfx**
This is an updated implementation of `findSequenceOnDisk` which adds a new `preserve_padding` flag. When enabled, the resulting sequence match will try and use the original padding characters, if provided in the source pattern, and if they are applicable to the padding of the sequence.

Given `strictPadding=True` the implementation is simple and is able to directly trust the original padding characters as an exact match.

When `strictPadding=False` the implementation is more complicated, because the original padding characters are only a placeholder and can't be guaranteed to reflect the real padding width of the frames. So we need to propagate the original padding characters only on the condition that they match resulting padding width. Furthermore, because a frame like "1001" can match padding widths of 1, 2, 3, or 4, we also need to track whether there are any padded frames in the results. If there are padded frames ("0001") then the padding width needs to exactly match (ie 4). If there are no padded frames ("1001") then we can also propagate the padding characters if they are less than or equal (1-4).

Fixes #112

### CODE REVIEW

**Comment by herronelou** [comment]
This seems like it will do the trick.

It would be neat to reduce the number of args in a future major version, as the logic starts to have many branches.
Similarly, when I added the UDIM syntax, I felt like it would be good to have a more fully-fledged Padding class, which can define the regex pattern, the number of padding digits, etc, as it felt I had to edit a few unrelated areas to implement it.

**Comment by justinfx** [comment]
I agree with both points. Within this same major version I always try to make sure to not suddenly change the behaviour in a way that would cause random pipeline breakage. But having too many feature flags isn't great. I would also like to use that opportunity to clean up the snake vs camel naming that has built up. But also, I would really love if a new major version was also a binding for C++ so that I don't have to maintain so many ports :-)

The padding class seems cool. I had a similar thought when I was reviewing the code. It feels related to the reason we had refactored the regex references into the FileSequence class to let developers subclass and modify the behavior without changing the global library.

**Comment by herronelou** [comment]
My issue with having the python only being a bind of c++ is... that it's a bind of c++. 
That most likely means not using it at work where we're not set up for compiling c++ and don't have internet access, harder to make changes unless we know how to code c++ and recompile, more difficult to integrate into projects and deploy/redistribute, etc... I don't know the implications with regards to compiling python bindings for c++, but we're using multiple python versions in parallel (dcc's embedded python, standalone 2.7, standalone 3.7, some 3.8, some 3.10), would you need a compiled binding for each?

I like the simplicity of copy/pasting some python code and being good to go.

**Comment by justinfx** [comment]
I can understand that a Python binding to C++ can make a project more complicated if you are required to build it. Is that a hard requirement or would you not be able to securely (air gap) download the artifacts if they were pre-build and pushed to pypi? Presumably a project that is using bindings would build multiple targets in CI (windows, linux, py2.7,3.7,3.8). 

As long as you have the right target build, usability should hopefully be the same. it is true that if your intention is to hack on the code-base, it would require some C++ knowledge. But ultimately we have to weigh the cost of maintaining multiple language ports vs making it easy for every user to hack on it in only python. I've no immediate plans to do this, but it was a future goal.

**Comment by herronelou** [comment]
If all the necessary builds are available through pypi it's a bit easier, while there is an air gap, it's possible to manually send stuff in. As long as the builds are compatible with dcc pythons should be ok.

**Pull request merged**
